from __future__ import annotations
import hashlib
import secrets
from datetime import datetime, timedelta, timezone

"""B0.1 -- AuthN foundation. Implements ADR-002's resolved design
(docs/B0_HOSTED_PLATFORM_SECURITY_FOUNDATION.md): email magic-link
login, no password system (password_hash stays NULLable on `users`),
API tokens for service/automation accounts, and a self-hosted
first-user console-token bootstrap. Deliberately does NOT implement:
organizations/roles (B0.2/B0.3 -- there is exactly one implicit scope,
the whole instance, in B0.1), a general per-route AuthZ/CSRF sweep
(B0.3/B0.4 -- current_user() is built here but not yet applied to any
of the 143 pre-existing routes), or password/social login (ADR-002's
own explicit deferrals). Every login/API token is stored HASHED
(SHA-256 -- correct for high-entropy random tokens generated by
secrets.token_urlsafe(), unlike a human-chosen password, which is why
this app has no bcrypt/argon2 dependency for these -- see ADR-002's
own dependency-minimalism rationale); the raw token is never persisted
anywhere, only returned once at issuance time, the same "never store
the raw secret" discipline ADR-001 applied to GitHub installation
tokens.

`AUTH_MODE=none` (default, unchanged) never calls any method here at
all -- every route that would is gated at the top of its own handler
in app/main.py, not inside this service."""

LOGIN_TOKEN_TTL_MINUTES = 15
LOGIN_EMAIL_COOLDOWN_SECONDS = 60  # ADR-002/ADR-003: launch-blocking, per-email throttle


def _hash_token(raw: str) -> str:
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _iso(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M:%S")


class AuthError(ValueError):
    def __init__(self, code: str, message: str):
        self.code = code
        super().__init__(message)


class AuthService:
    def __init__(self, db, email_sender):
        self.db = db
        self.email_sender = email_sender

    # ---- users -----------------------------------------------------
    def get_user(self, user_id: int) -> dict | None:
        return self.db.one("SELECT * FROM users WHERE id=?", (user_id,))

    def get_user_by_email(self, email: str) -> dict | None:
        return self.db.one("SELECT * FROM users WHERE email=?", (email.strip().lower(),))

    def user_count(self) -> int:
        return self.db.one("SELECT COUNT(*) c FROM users")["c"]

    def _create_user(self, email: str) -> dict:
        uid = self.db.execute("INSERT INTO users(email) VALUES(?)", (email.strip().lower(),))
        self.db.event("user", uid, "USER_CREATED", email.strip().lower())
        return self.get_user(uid)

    def get_or_create_user(self, email: str) -> dict:
        """B0.2's own entry point (OrganizationService.accept_invitation())
        for the ONLY other place a user account is ever created besides
        the B0.1 bootstrap flow -- public, unlike _create_user(), since
        it's a cross-service call, not an internal implementation detail."""
        return self.get_user_by_email(email) or self._create_user(email)

    # ---- magic-link login (ADR-002) --------------------------------
    def request_login(self, email: str) -> None:
        """ADR-002's own enumeration mitigation: this method NEVER
        signals whether the email is registered via its return value or
        by raising -- callers must always show the identical "if an
        account exists, we sent a link" response regardless. B0.1 has
        no open self-registration (see the B0.1 implementation report /
        ADR-002's own scope note): a request for an unregistered email
        silently does nothing beyond this point."""
        email = (email or "").strip().lower()
        if not email or "@" not in email:
            return
        user = self.get_user_by_email(email)
        if not user:
            return
        # Per-email cooldown (ADR-002/ADR-003): DB-backed, not in-memory
        # -- correct across multiple processes/instances by construction,
        # unlike a naive in-memory counter, without needing the
        # distributed rate-limit library ADR-003 reserved for the
        # general per-IP case.
        recent = self.db.one(
            "SELECT created_at FROM login_tokens WHERE email=? ORDER BY id DESC LIMIT 1", (email,))
        if recent:
            recent_at = datetime.strptime(recent["created_at"], "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
            if _now() - recent_at < timedelta(seconds=LOGIN_EMAIL_COOLDOWN_SECONDS):
                return
        raw_token = secrets.token_urlsafe(32)
        expires_at = _now() + timedelta(minutes=LOGIN_TOKEN_TTL_MINUTES)
        self.db.execute(
            "INSERT INTO login_tokens(user_id,email,token_hash,expires_at) VALUES(?,?,?,?)",
            (user["id"], email, _hash_token(raw_token), _iso(expires_at)))
        self.db.event("user", user["id"], "LOGIN_LINK_REQUESTED", email)
        self.email_sender.send(
            email, "Sign in to ProjectFlow",
            f"Click to confirm sign-in (expires in {LOGIN_TOKEN_TTL_MINUTES} minutes):\n\n"
            f"/auth/verify?token={raw_token}\n\nIf you didn't request this, ignore this email.")

    def peek_login_token(self, raw_token: str) -> dict | None:
        """Read-only lookup for the confirm-click landing page (ADR-002's
        own phishing mitigation: a GET must be able to show WHICH email
        is being confirmed without consuming the token -- consumption
        only happens in consume_login_token(), on the follow-up POST)."""
        if not raw_token:
            return None
        row = self.db.one("SELECT * FROM login_tokens WHERE token_hash=?", (_hash_token(raw_token),))
        if not row or row["used_at"]:
            return None
        expires_at = datetime.strptime(row["expires_at"], "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
        if _now() > expires_at:
            return None
        return row

    def consume_login_token(self, raw_token: str) -> dict:
        """Single-use: the token is marked used_at in the SAME call that
        validates it -- never a separate 'check then use' race, and a
        second POST with the same token always fails from here on."""
        row = self.peek_login_token(raw_token)
        if not row:
            raise AuthError("LOGIN_TOKEN_INVALID", "This sign-in link is invalid, expired, or already used.")
        self.db.execute("UPDATE login_tokens SET used_at=CURRENT_TIMESTAMP WHERE id=?", (row["id"],))
        self.db.execute("UPDATE users SET last_login_at=CURRENT_TIMESTAMP WHERE id=?", (row["user_id"],))
        self.db.event("user", row["user_id"], "LOGIN_SUCCEEDED", row["email"])
        return self.get_user(row["user_id"])

    # ---- self-hosted first-user bootstrap (ADR-002) -----------------
    def bootstrap(self, raw_token: str, bootstrap_token_hash: str, email: str) -> dict:
        """Only ever valid while zero users exist AND the token matches
        the one this process printed to its own log at startup (held in
        app.state, never persisted -- a restart before setup simply
        reprints a fresh one, which is a safety property, not a bug).
        Creates the user and returns it in one step -- no separate email
        round-trip, since the token itself was already delivered
        out-of-band (the operator's own console/log), exactly ADR-002's
        own stated reason this exists."""
        if self.user_count() > 0:
            raise AuthError("BOOTSTRAP_CLOSED", "Setup has already completed on this instance.")
        if not raw_token or not secrets.compare_digest(_hash_token(raw_token), bootstrap_token_hash):
            raise AuthError("BOOTSTRAP_TOKEN_INVALID", "Invalid setup token.")
        email = (email or "").strip().lower()
        if not email or "@" not in email:
            raise AuthError("BOOTSTRAP_EMAIL_INVALID", "Enter a valid email address.")
        user = self._create_user(email)
        self.db.execute("UPDATE users SET last_login_at=CURRENT_TIMESTAMP WHERE id=?", (user["id"],))
        self.db.event("user", user["id"], "BOOTSTRAP_COMPLETED", email)
        return user

    # ---- API tokens (service/automation accounts) -------------------
    def create_api_token(self, user_id: int, name: str) -> tuple[dict, str]:
        """Returns (row, raw_token) -- the raw token is returned exactly
        once, here, and never again; only its hash and a short display
        prefix are ever persisted."""
        raw_token = "pf_" + secrets.token_urlsafe(32)
        tid = self.db.execute(
            "INSERT INTO api_tokens(user_id,name,token_hash,token_prefix) VALUES(?,?,?,?)",
            (user_id, (name or "").strip() or "Unnamed token", _hash_token(raw_token), raw_token[:10]))
        self.db.event("user", user_id, "API_TOKEN_CREATED", (name or "").strip())
        return self.db.one("SELECT * FROM api_tokens WHERE id=?", (tid,)), raw_token

    def list_api_tokens(self, user_id: int) -> list[dict]:
        return self.db.all("SELECT id,name,token_prefix,created_at,last_used_at,revoked_at FROM api_tokens "
                            "WHERE user_id=? ORDER BY id DESC", (user_id,))

    def revoke_api_token(self, user_id: int, token_id: int) -> None:
        row = self.db.one("SELECT * FROM api_tokens WHERE id=? AND user_id=?", (token_id, user_id))
        if not row:
            raise AuthError("API_TOKEN_NOT_FOUND", "Token not found.")
        self.db.execute("UPDATE api_tokens SET revoked_at=CURRENT_TIMESTAMP WHERE id=?", (token_id,))
        self.db.event("user", user_id, "API_TOKEN_REVOKED", row["name"])

    def user_for_api_token(self, raw_token: str) -> dict | None:
        if not raw_token:
            return None
        row = self.db.one("SELECT * FROM api_tokens WHERE token_hash=?", (_hash_token(raw_token),))
        if not row or row["revoked_at"]:
            return None
        self.db.execute("UPDATE api_tokens SET last_used_at=CURRENT_TIMESTAMP WHERE id=?", (row["id"],))
        return self.get_user(row["user_id"])
