from __future__ import annotations
import json

"""Phase E13: Parallel Multi-Agent Execution & Integration Waves --
Parallel Safety Analysis (E13.1-E13.5).

CORE SAFETY PRINCIPLE (E13's own instruction, restated because it
drives every rule below): only run Tasks in parallel when ProjectFlow
can justify their execution is independent enough. UNKNOWN MUST
DEFAULT TO SERIAL -- absence of evidence is never proof of safety.

Deterministic evidence only (E13.1: "E13 must not depend on LLM to
prove basic execution safety"). Every signal here is real, already-
existing truth -- task_dependencies (direct+transitive, reusing
TaskDependencyService._reaches verbatim), tasks.fix_of_task_id lineage
(reusing review_service.task_chain_ids verbatim), plan_items.
scope_hints/exclusive_resources, and a small set of deterministic
path-pattern classifiers (migration/manifest/global-config/generated-
singleton files) -- never a second dependency/scope engine."""

from app.services.review_service import task_chain_ids

PARALLEL_RESULTS = ("PARALLEL_SAFE", "PARALLEL_CONFLICT", "PARALLEL_DEPENDENCY", "PARALLEL_UNKNOWN", "PARALLEL_BLOCKED")

# E13.3 rule 6: migration/schema paths.
_MIGRATION_PATTERNS = ("migrations/", "migration/", "alembic/", "schema.sql", "schema.py")
# E13.3 rule 7: dependency manifests -- ANY of these touched by both
# Tasks conflicts, even if not the identical file, since these interact
# codebase-wide (a lockfile regenerated by one Task invalidates the
# other's own install state).
_MANIFEST_FILES = ("package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "requirements.txt",
                    "pyproject.toml", "poetry.lock", "Pipfile", "Pipfile.lock", "Cargo.toml", "Cargo.lock",
                    "go.mod", "go.sum", "Gemfile", "Gemfile.lock")
# E13.3 rule 8: global/shared configuration.
_GLOBAL_CONFIG_FILES = ("PROJECT.yaml", ".env", "docker-compose.yml", "docker-compose.yaml", "Dockerfile",
                         "settings.py", "config.py", "config.yaml", "config.yml")
# E13.3 rule 9: version/generated singleton files.
_GENERATED_SINGLETON_PATTERNS = ("VERSION", "CHANGELOG.md", "generated/", "__generated__/")


def _matches_any(path: str, patterns) -> bool:
    low = path.lower()
    return any(p.lower() in low for p in patterns)


def _basename_in(path: str, names) -> bool:
    base = path.rsplit("/", 1)[-1]
    return base in names


class ParallelSafetyService:
    def __init__(self, db, task_dependencies, project_policy_resolver=None):
        self.db = db
        self.task_dependencies = task_dependencies
        self.project_policy_resolver = project_policy_resolver

    # ---- E13.2: raw signals for one Task ---------------------------------
    def _plan_item(self, task_id: int) -> dict | None:
        return self.db.one("SELECT * FROM plan_items WHERE materialized_task_id=?", (task_id,))

    def conflicts_for_task(self, task_id: int) -> dict:
        """The declared-evidence surface for one Task -- scope_hints,
        exclusive_resources, and the deterministic classification of
        each declared path (migration/manifest/global-config/generated)
        -- used both by evaluate_pair() and surfaced directly via
        GET /api/tasks/{id}/parallel-conflicts (E13.40)."""
        pi = self._plan_item(task_id)
        scope = json.loads(pi["scope_hints"] or "[]") if pi else []
        resources = json.loads(pi["exclusive_resources"] or "[]") if pi else []
        return {
            "task_id": task_id, "repository_id": self._repo_for_task(task_id),
            "scope_hints": scope, "exclusive_resources": resources,
            "touches_migration": any(_matches_any(p, _MIGRATION_PATTERNS) for p in scope),
            "touches_manifest": any(_basename_in(p, _MANIFEST_FILES) for p in scope),
            "touches_global_config": any(_basename_in(p, _GLOBAL_CONFIG_FILES) for p in scope),
            "touches_generated_singleton": any(_matches_any(p, _GENERATED_SINGLETON_PATTERNS) for p in scope),
        }

    def _repo_for_task(self, task_id: int) -> int | None:
        row = self.db.one(
            "SELECT aw.repository_id FROM agent_workspaces aw WHERE aw.task_id=? ORDER BY aw.id DESC LIMIT 1", (task_id,))
        if row:
            return row["repository_id"]
        t = self.db.one("SELECT change_id FROM tasks WHERE id=?", (task_id,))
        if not t or not t["change_id"]:
            return None
        c = self.db.one("SELECT project_id FROM changes WHERE id=?", (t["change_id"],))
        return c["project_id"] if c else None

    def _policy(self, task_id: int) -> dict:
        if not self.project_policy_resolver:
            return {}
        t = self.db.one("SELECT change_id FROM tasks WHERE id=?", (task_id,))
        change = self.db.one("SELECT * FROM changes WHERE id=?", (t["change_id"],)) if t and t["change_id"] else None
        return (self.project_policy_resolver(change) or {}) if change else {}

    # ---- E13.3: hard conflict rules (never overridable by policy) --------
    def evaluate_pair(self, task_a_id: int, task_b_id: int) -> dict:
        if task_a_id == task_b_id:
            return {"result": "PARALLEL_BLOCKED", "reasons": ["SAME_TASK"]}

        # 1/2/14: direct or transitive dependency in either direction --
        # one Task's output feeding the other's Builder context is
        # exactly what a real dependency edge already means.
        if self.task_dependencies._reaches(task_a_id, task_b_id) or self.task_dependencies._reaches(task_b_id, task_a_id):
            return {"result": "PARALLEL_DEPENDENCY", "reasons": ["TASK_DEPENDENCY"]}

        # 4: one is FIX/review-dependent on the other's own change --
        # reuses E9's own fix-lineage walk verbatim.
        chain_a, chain_b = set(task_chain_ids(self.db, task_a_id)), set(task_chain_ids(self.db, task_b_id))
        if chain_a & chain_b:
            return {"result": "PARALLEL_DEPENDENCY", "reasons": ["FIX_LINEAGE"]}

        ca, cb = self.conflicts_for_task(task_a_id), self.conflicts_for_task(task_b_id)
        reasons: list[str] = []

        # 3: same worktree (a Task can only ever have one managed
        # worktree per repository -- this only fires if the SAME task_id
        # was passed twice under a different alias, already covered
        # above by the == check, kept here for explicitness/audit).

        # 5: explicit scope overlap on the same file/path (prefix-aware,
        # same containment rule check_scope_violation already uses).
        def _in_scope(path, scope):
            return any(path == s or path.startswith(s.rstrip("/") + "/") or s.startswith(path.rstrip("/") + "/") for s in scope)
        overlap = [p for p in ca["scope_hints"] for q in cb["scope_hints"] if _in_scope(p, [q]) or _in_scope(q, [p])]
        if overlap:
            reasons.append("SCOPE_OVERLAP")

        # 6: both touch migration/schema paths.
        if ca["touches_migration"] and cb["touches_migration"]:
            reasons.append("MIGRATION_CONFLICT")
        # 7: both touch a dependency manifest.
        if ca["touches_manifest"] and cb["touches_manifest"]:
            reasons.append("MANIFEST_CONFLICT")
        # 8: both touch global/shared configuration.
        if ca["touches_global_config"] and cb["touches_global_config"]:
            reasons.append("GLOBAL_CONFIG_CONFLICT")
        # 9: both touch a version/generated singleton.
        if ca["touches_generated_singleton"] and cb["touches_generated_singleton"]:
            reasons.append("GENERATED_SINGLETON_CONFLICT")
        # 10/13: declared exclusive resources intersect (also how a
        # shared runtime resource -- a fixed port, a Docker Compose
        # project, a shared test DB -- gets declared per E13.13/E13.21).
        shared_resources = set(ca["exclusive_resources"]) & set(cb["exclusive_resources"])
        if shared_resources:
            reasons.append("EXCLUSIVE_RESOURCE_CONFLICT")

        if reasons:
            return {"result": "PARALLEL_CONFLICT", "reasons": reasons, "overlap_files": overlap,
                     "shared_resources": sorted(shared_resources)}

        # 12: repository policy forces serial execution.
        repo_id = ca.get("repository_id") or cb.get("repository_id")
        if repo_id:
            policy = self._policy(task_a_id)
            if (policy.get("parallel_execution") or {}).get("repository_serial"):
                return {"result": "PARALLEL_CONFLICT", "reasons": ["REPOSITORY_SERIAL_EXECUTION"]}
            if (policy.get("parallel_execution") or {}).get("parallel_test_safe") is False:
                return {"result": "PARALLEL_CONFLICT", "reasons": ["PARALLEL_TEST_SAFE_DISABLED"]}

        # E13.5: weak/absent scope evidence is never proof of safety.
        # 11 (architecture/design contract consumption) has no reliable
        # deterministic Task-granularity signal yet -- folded into this
        # same conservative UNKNOWN default rather than a fabricated
        # classifier (documented, not silently assumed safe).
        if not ca["scope_hints"] or not cb["scope_hints"]:
            return {"result": "PARALLEL_UNKNOWN", "reasons": ["INSUFFICIENT_SCOPE_EVIDENCE"]}

        return {"result": "PARALLEL_SAFE", "reasons": []}

    # ---- candidate-set selection (deterministic, order-preserving) -------
    def evaluate_candidate_set(self, task_ids: list[int]) -> dict:
        """Pairwise matrix + a deterministic greedy selection in the
        given order (callers pass an already dependency-depth-ordered
        list -- see AutonomousExecutionService.list_auto_ready_tasks):
        a candidate joins the safe set only if it is PARALLEL_SAFE
        against EVERY task already selected; the first candidate is
        always includable on its own."""
        selected: list[int] = []
        deferred: list[dict] = []
        pairwise: dict[str, dict] = {}
        for tid in task_ids:
            conflict = None
            for sid in selected:
                key = f"{min(tid, sid)}:{max(tid, sid)}"
                if key not in pairwise:
                    pairwise[key] = self.evaluate_pair(tid, sid)
                result = pairwise[key]
                if result["result"] != "PARALLEL_SAFE":
                    conflict = {"against": sid, **result}
                    break
            if conflict is None:
                selected.append(tid)
            else:
                deferred.append({"task_id": tid, "reason": conflict["result"], "detail": conflict})
        return {"selected": selected, "deferred": deferred, "pairwise": pairwise}
