from __future__ import annotations
import hashlib
import json

"""Test Design, Requirement Coverage & Executable Acceptance Mapping
(Phase E7): Approved Spec -> Acceptance Criteria -> Test Design ->
Requirement Coverage -> Executable Test Mapping -> Test Review ->
TEST_DESIGN_READY.

CRITICAL SEPARATION, enforced by construction across five classes,
mirroring E5/E6's own AUTHOR/ARTIFACT/REVIEWER/APPROVAL separation
(E7's own instruction: keep SPEC / TEST SPECIFICATION / EXECUTABLE TEST
/ TEST RESULT / SPEC COMPLIANCE separate -- never a single "tests
passed" boolean):

  TEST SPECIFICATION (HOW behavior will be proven) -- TestDesignService
    + the test_case_specs table. One bounded, stateless, tool-less
    PlannerAgentInvoker.invoke() call (the same shared mechanism E4/E5/
    E6 use) that returns STRUCTURED TestCaseSpecs. Expected outcome is
    always taken from the approved Requirement/AcceptanceCriterion/
    Invariant text handed to it, never derived from current
    implementation (E7.5) -- this service has no repository-code
    reading path at all, so there is nothing for it to derive from.

  REQUIREMENT COVERAGE (deterministic, never trusts the model) --
    RequirementCoverageService. Recomputes requirements_covered/
    uncovered, acceptance_covered/uncovered, invariants_covered/
    uncovered directly from real SpecRegistry ids cross-referenced
    against the TestCaseSpecs' own requirement_ids/acceptance_ids/
    invariant_ids columns. A model-claimed coverage total is never
    trusted as authoritative (matches TechnicalDesignService's own
    covered_requirements/uncovered_requirements precedent, E6.9).

  TEST REVIEW (independent invocation) -- TestReviewService. A
    COMPLETELY SEPARATE invoke() call reviewing the TestCaseSpecs
    against the real coverage report, never the author's own reasoning.

  EXECUTABLE TEST MAPPING (a TestCaseSpec's implementation, not its
    result) -- ExecutableTestMappingService + test_executable_mappings.
    Explicit, human/API-confirmed linkage only (E7.14: no unreliable
    semantic repo-wide guessing); UNIMPLEMENTED/IMPLEMENTED/PASS/FAIL
    are the only states this module ever writes.

  TEST RESULT / SPEC COMPLIANCE -- untouched here. test_runs/
  verification_reports/EvidenceStore/SpecComplianceVerifier remain the
  ONLY place a test actually ran and what it proved is recorded --
  see app/services/spec_compliance.py's own E7 additions for how a
  designed-but-never-executed TestCaseSpec is distinguished from real
  execution evidence. A TestCaseSpec, however completely designed, is
  NEVER itself treated as evidence that anything actually passed.

No implementation Task is ever generated by this module (E7.15) --
Planner (E4) remains the only thing that ever creates a Task; this
module only exposes test_implementation_required/unimplemented_test_cases
to PlannerContextBuilder (see app/services/planner_service.py)."""

from app.services.human_decisions import HumanDecisionService

TEST_LEVELS = (
    "UNIT", "INTEGRATION", "CONTRACT", "API", "UI", "END_TO_END",
    "MIGRATION", "RUNTIME", "SECURITY", "PERFORMANCE", "MANUAL_ACCEPTANCE",
)
TEST_TYPES = ("POSITIVE", "NEGATIVE", "BOUNDARY", "MANUAL_ACCEPTANCE")
TEST_CASE_STATUSES = ("DRAFT", "APPROVED", "REJECTED", "SUPERSEDED")
IMPLEMENTATION_STATUSES = ("UNIMPLEMENTED", "IMPLEMENTED", "PASS", "FAIL")
REVIEW_VERDICTS = ("PASS", "NEEDS_REFINEMENT", "HUMAN_DECISION_REQUIRED", "REJECT")


class TestDesignError(ValueError):
    pass


# ===================================================================
# Structured output schemas
# ===================================================================
_TEST_CASE_BLOCK = {
    "type": "array",
    "items": {
        "type": "object",
        "required": ["key", "title", "test_level", "expected_results"],
        "properties": {
            "key": {"type": "string"},
            "source_feature_id": {"type": "string"},
            "requirement_ids": {"type": "array", "items": {"type": "string"}},
            "acceptance_ids": {"type": "array", "items": {"type": "string"}},
            "invariant_ids": {"type": "array", "items": {"type": "string"}},
            "test_level": {"type": "string", "enum": list(TEST_LEVELS)},
            "test_type": {"type": "string", "enum": list(TEST_TYPES)},
            "title": {"type": "string"},
            "purpose": {"type": "string"},
            "preconditions": {"type": "string"},
            "setup": {"type": "string"},
            "action": {"type": "string"},
            "expected_results": {"type": "string"},
            "failure_expectations": {"type": "string"},
            "data_requirements": {"type": "string"},
            "environment_requirements": {"type": "string"},
            "automation_candidate": {"type": "boolean"},
            "execution_hint": {"type": "string"},
        },
    },
}

TEST_DESIGN_JSON_SCHEMA = {
    "type": "object",
    "required": ["strategy_summary", "test_cases"],
    "properties": {
        "strategy_summary": {"type": "string"},
        "test_cases": _TEST_CASE_BLOCK,
        "untestable_or_ambiguous_items": {"type": "array", "items": {"type": "string"}},
        "implementation_spec_conflicts": {"type": "array", "items": {"type": "string"}},
        "human_decisions": {
            "type": "array",
            "items": {
                "type": "object", "required": ["question", "reason"],
                "properties": {"question": {"type": "string"}, "reason": {"type": "string"},
                                "decision_type": {"type": "string", "enum": [
                                    "AMBIGUOUS_BEHAVIOR", "UX_OUTCOME", "BUSINESS_RULE", "FAILURE_BEHAVIOR", "OTHER"]}},
            },
        },
    },
}

TEST_REVIEW_JSON_SCHEMA = {
    "type": "object",
    "required": ["verdict"],
    "properties": {
        "verdict": {"type": "string", "enum": list(REVIEW_VERDICTS)},
        "findings": {
            "type": "array",
            "items": {
                "type": "object", "required": ["category", "description"],
                "properties": {
                    "category": {"type": "string", "enum": [
                        "behavior_coverage", "missing_edge_case", "weak_assertion", "mirrors_implementation",
                        "false_positive_risk", "unobservable_expectation", "missing_negative_path",
                        "missing_persistence_restart_case", "migration_rollback_coverage", "ui_state_coverage",
                        "security_sensitive_case", "requirement_trace"]},
                    "severity": {"type": "string", "enum": ["LOW", "MEDIUM", "HIGH"]},
                    "description": {"type": "string"},
                    "suggested_fix": {"type": "string"},
                    "test_case_key": {"type": "string"},
                },
            },
        },
        "human_decisions": {
            "type": "array",
            "items": {"type": "object", "required": ["question", "reason"],
                       "properties": {"question": {"type": "string"}, "reason": {"type": "string"}}},
        },
    },
}

TEST_DESIGNER_PREAMBLE = """You are the TEST DESIGNER for ProjectFlow, an autonomous software engineering control plane.

Core principles: Human owns intent; Spec owns expected behavior; Architecture owns boundaries; Design owns the technical solution -- you own HOW expected behavior will be PROVEN. You never write source or test files yourself.

Design TestCaseSpecs strictly from the approved Requirements/AcceptanceCriteria/Invariants below. The expected_results of every test case MUST come from the spec text, never from current implementation or design details you weren't given -- architecture/design context may only inform HOW to test (test level, environment, setup), never WHAT the correct outcome is. If the design context appears to contradict the spec, report it in implementation_spec_conflicts and still design the test case's expected_results from the SPEC, never silently matching what the design implies instead.

Cover, where the spec actually calls for it: the positive/happy path, explicit negative/failure cases (invalid input, denied permission, a failed dependency), boundary cases, and (only when Technical Design says migration/rollback is required) a MIGRATION-level test, and (only when Technical Design says runtime behavior matters) a RUNTIME-level test. Use test_type=MANUAL_ACCEPTANCE for genuinely subjective UX judgment that cannot be automated -- never fake automation for it.

Every requirement_ids/acceptance_ids/invariant_ids entry must be a real id from the spec context below -- ProjectFlow will independently re-verify every one against the real SpecRegistry and silently discard any that don't resolve, so a fictional id only produces a false sense of coverage that a later check will catch.

If continuing requires a decision that changes WHAT is expected (business rule, ambiguous behavior, materially different UX outcome, unclear destructive-failure behavior) -- add it to human_decisions instead of guessing. Never ask a human about pytest vs unittest, selector strategy, fixture shape, mocking, or file layout -- those are yours to decide (and irrelevant here since you don't write the files)."""

TEST_REVIEWER_PREAMBLE = """You are an INDEPENDENT TEST REVIEWER for ProjectFlow. You are a fresh reviewer with no memory of how this test design was produced -- judge only what is in front of you.

Review the TestCaseSpecs below against the original human intent, approved spec, architecture/design, and the DETERMINISTIC coverage report (computed by ProjectFlow itself, not by the test designer) also provided. Check explicitly for: behavior coverage, missing edge cases, weak assertions, tests that merely mirror the implementation rather than proving the spec, false-positive risk, unobservable expectations, missing negative paths, missing persistence/restart cases, migration/rollback coverage, UI state coverage, security-sensitive cases, and requirement-trace correctness (does each cited id actually match what the test case does?).

Verdict:
- PASS only if there is nothing worth fixing.
- NEEDS_REFINEMENT for concrete, fixable coverage/quality issues -- describe exactly what to fix, and reference the test_case_key when you can.
- HUMAN_DECISION_REQUIRED only if a finding requires a real product-level/business-rule/UX decision a human must make.
- REJECT only if the test design is fundamentally unusable as written.

Never suggest weakening a requirement, removing a difficult acceptance criterion, or marking something covered without an actual TestCaseSpec that proves it, merely to make coverage look complete."""


def _resolve_id_collisions_free(items: list[str]) -> list[str]:
    """No collision remapping needed for id REFERENCES (unlike E5's
    authored ids) -- just dedupe while preserving order."""
    seen: set[str] = set()
    out: list[str] = []
    for it in items or []:
        s = (it or "").strip()
        if s and s not in seen:
            seen.add(s)
            out.append(s)
    return out


class _TestAgentRole:
    """Shared plumbing for every E7 agent role -- same shape as E5/E6's
    own _AgentRole, duplicated rather than imported so this module stays
    self-contained."""

    def __init__(self, db, invoker, roles_catalog, role_key):
        self.db = db
        self.invoker = invoker
        self.roles_catalog = roles_catalog
        self.role_key = role_key

    def _check_assignment(self, provider):
        assignment = self.roles_catalog.validate_assignment(provider, self.role_key)
        if not assignment["valid"]:
            raise TestDesignError(f"Provider '{provider}' cannot act as {self.role_key}: missing {assignment['missing_required_capabilities']}")


# ===================================================================
# TestCaseSpec store -- a thin domain/table (E7.3) over test_case_specs
# ===================================================================
class TestCaseSpecStore:
    def __init__(self, db):
        self.db = db

    def get(self, tcs_id: int) -> dict | None:
        return self.db.one("SELECT * FROM test_case_specs WHERE id=?", (tcs_id,))

    def list_for_change(self, change_id: int, current_only: bool = True) -> list[dict]:
        if current_only:
            return self.db.all("SELECT * FROM test_case_specs WHERE change_id=? AND status!='SUPERSEDED' ORDER BY id", (change_id,))
        return self.db.all("SELECT * FROM test_case_specs WHERE change_id=? ORDER BY id", (change_id,))

    def list_for_work_product(self, work_product_id: int) -> list[dict]:
        return self.db.all("SELECT * FROM test_case_specs WHERE work_product_id=? ORDER BY id", (work_product_id,))

    def set_status(self, tcs_id: int, status: str) -> dict:
        status = (status or "").strip().upper()
        if status not in TEST_CASE_STATUSES:
            raise TestDesignError(f"Unknown status: {status} (must be one of {TEST_CASE_STATUSES})")
        if not self.get(tcs_id):
            raise TestDesignError("TestCaseSpec not found")
        self.db.execute("UPDATE test_case_specs SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?", (status, tcs_id))
        return self.get(tcs_id)

    def set_status_for_work_product(self, work_product_id: int, status: str) -> None:
        for row in self.list_for_work_product(work_product_id):
            self.set_status(row["id"], status)


# ===================================================================
# Bounded Test Design context (mirrors ArchitectureContextBuilder, E6.4)
# ===================================================================
class TestDesignContextBuilder:
    def __init__(self, db, changes, work_products, trace, test_case_specs: TestCaseSpecStore, specs_root):
        self.db = db
        self.changes = changes
        self.work_products = work_products
        self.trace = trace
        self.test_case_specs = test_case_specs
        self.specs_root = specs_root

    def governing_feature_ids(self, change_id: int) -> list[str]:
        return [l["target_id"] for l in self.trace.for_source("change", change_id) if l["target_type"] == "spec_feature"]

    def build(self, change_id: int, project_test_command: dict | None = None) -> dict:
        from app.services.spec_registry import SpecRegistry, SpecError
        change = self.changes.get(change_id)
        governing_ids = self.governing_feature_ids(change_id)
        governing_specs: list[dict] = []
        all_requirement_ids: list[str] = []
        all_acceptance_ids: list[str] = []
        all_invariant_ids: list[str] = []
        try:
            registry = SpecRegistry(self.specs_root).load()
            for fid in governing_ids:
                f = registry.feature(fid)
                if not f:
                    continue
                governing_specs.append({
                    "id": f["id"], "title": f.get("title"), "summary": f.get("summary"),
                    "requirements": f.get("requirements") or [], "acceptance_criteria": f.get("acceptance_criteria") or [],
                    "invariants": f.get("invariants") or [],
                })
                all_requirement_ids.extend(r["id"] for r in (f.get("requirements") or []))
                all_acceptance_ids.extend(a["id"] for a in (f.get("acceptance_criteria") or []))
                all_invariant_ids.extend(i["id"] for i in (f.get("invariants") or []))
        except SpecError:
            pass

        design_kinds = ("ARCHITECTURE_ANALYSIS", "TECHNICAL_DESIGN", "UI_UX_DESIGN")
        design_context = []
        for wp in self.work_products.list_for_change(change_id):
            if wp["kind"] in design_kinds and wp["status"] == "APPROVED":
                design_context.append({"kind": wp["kind"], "id": wp["id"], "content": json.loads(wp["content_metadata"] or "{}")})

        existing_test_work = [
            {"kind": wp["kind"], "title": wp["title"], "status": wp["status"], "id": wp["id"]}
            for wp in self.work_products.list_for_change(change_id)
            if wp["kind"] in ("TEST_PLAN", "TEST_CASE_SET", "TEST_REVIEW", "REQUIREMENT_COVERAGE_REPORT") and wp["status"] != "SUPERSEDED"
        ]
        existing_test_cases = [
            {"key": tc["item_key"], "title": tc["title"], "test_level": tc["test_level"],
             "requirement_ids": json.loads(tc["requirement_ids"] or "[]")}
            for tc in self.test_case_specs.list_for_change(change_id)
        ]

        return {
            "change": {"id": change_id, "title": change.get("title") if change else None,
                       "original_intent": change.get("description") if change else None,
                       "change_type": change.get("change_type") if change else None},
            "governing_specs": governing_specs,
            "all_requirement_ids": sorted(set(all_requirement_ids)),
            "all_acceptance_ids": sorted(set(all_acceptance_ids)),
            "all_invariant_ids": sorted(set(all_invariant_ids)),
            "architecture_and_design": design_context,
            "project_test_command": project_test_command or {},
            "existing_test_work": existing_test_work,
            "existing_test_cases": existing_test_cases,
        }


# ===================================================================
# Test Design (E7.4/E7.5) -- expected outcome always from spec, never
# from current implementation (this service has no repo-read path)
# ===================================================================
def _staleness_digest(context: dict) -> str:
    """E7.21: digest used for TEST_SPEC_STALE detection -- deliberately
    excludes project_test_command (caller-supplied per-request, not
    persisted anywhere retrievable for a later staleness re-check) so a
    staleness check that omits it never produces a false positive
    against a design call that included it."""
    stable = {k: v for k, v in context.items() if k != "project_test_command"}
    return hashlib.sha256(json.dumps(stable, sort_keys=True).encode()).hexdigest()


class TestDesignService(_TestAgentRole):
    def __init__(self, db, changes, work_products, invoker, roles_catalog, context_builder: TestDesignContextBuilder,
                 test_case_specs: TestCaseSpecStore, specs_root, repo_root):
        super().__init__(db, invoker, roles_catalog, "TEST_DESIGNER")
        self.changes = changes
        self.work_products = work_products
        self.context_builder = context_builder
        self.test_case_specs = test_case_specs
        self.specs_root = specs_root
        self.repo_root = repo_root

    def current_test_case_set(self, change_id: int) -> dict | None:
        rows = [wp for wp in self.work_products.list_for_change(change_id) if wp["kind"] == "TEST_CASE_SET" and wp["status"] != "SUPERSEDED"]
        return rows[-1] if rows else None

    def current_test_plan(self, change_id: int) -> dict | None:
        rows = [wp for wp in self.work_products.list_for_change(change_id) if wp["kind"] == "TEST_PLAN" and wp["status"] != "SUPERSEDED"]
        return rows[-1] if rows else None

    def _known_ids(self):
        from app.services.spec_registry import SpecRegistry, SpecError
        try:
            registry = SpecRegistry(self.specs_root).load()
            return set(registry.requirements.keys()), set(registry.acceptance.keys()), set(registry.invariants.keys())
        except SpecError:
            return set(), set(), set()

    def _store(self, change_id, provider, parsed, digest, supersedes_plan_id, supersedes_set_id) -> dict:
        change = self.changes.get(change_id)
        known_req, known_acc, known_inv = self._known_ids()

        plan_wp_id = self.work_products.create(
            kind="TEST_PLAN", title=f"Test Plan for {change['title'] if change else change_id}",
            project_id=change.get("project_id") if change else None, change_id=change_id, status="DRAFT",
            content_metadata={"strategy_summary": parsed.get("strategy_summary") or "",
                               "untestable_or_ambiguous_items": parsed.get("untestable_or_ambiguous_items") or [],
                               "implementation_spec_conflicts": parsed.get("implementation_spec_conflicts") or []},
            content_digest=digest, supersedes_id=supersedes_plan_id)

        set_wp_id = self.work_products.create(
            kind="TEST_CASE_SET", title=f"Test Cases for {change['title'] if change else change_id}",
            project_id=change.get("project_id") if change else None, change_id=change_id, status="DRAFT",
            content_ref=f"test_plan:{plan_wp_id}", supersedes_id=supersedes_set_id)

        with self.db.connect() as conn:
            keys_seen: set[str] = set()
            for i, tc in enumerate(parsed.get("test_cases") or []):
                key = (tc.get("key") or "").strip() or f"TC-{i+1}"
                if key in keys_seen:
                    key = f"{key}-{i+1}"
                keys_seen.add(key)
                req_ids = [r for r in _resolve_id_collisions_free(tc.get("requirement_ids")) if r in known_req]
                acc_ids = [a for a in _resolve_id_collisions_free(tc.get("acceptance_ids")) if a in known_acc]
                inv_ids = [v for v in _resolve_id_collisions_free(tc.get("invariant_ids")) if v in known_inv]
                test_level = (tc.get("test_level") or "").strip().upper()
                if test_level not in TEST_LEVELS:
                    test_level = "INTEGRATION"
                test_type = (tc.get("test_type") or "POSITIVE").strip().upper()
                if test_type not in TEST_TYPES:
                    test_type = "POSITIVE"
                conn.execute(
                    "INSERT OR IGNORE INTO test_case_specs(change_id,work_product_id,item_key,source_feature_id,requirement_ids,"
                    "acceptance_ids,invariant_ids,test_level,test_type,title,purpose,preconditions,setup,action,expected_results,"
                    "failure_expectations,data_requirements,environment_requirements,automation_candidate,execution_hint,status) "
                    "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                    (change_id, set_wp_id, key, tc.get("source_feature_id"), json.dumps(req_ids), json.dumps(acc_ids),
                     json.dumps(inv_ids), test_level, test_type, tc.get("title") or key, tc.get("purpose") or "",
                     tc.get("preconditions") or "", tc.get("setup") or "", tc.get("action") or "",
                     tc.get("expected_results") or "", tc.get("failure_expectations") or "", tc.get("data_requirements") or "",
                     tc.get("environment_requirements") or "", 1 if tc.get("automation_candidate", True) else 0,
                     tc.get("execution_hint") or "", "DRAFT"))

        hd_ids = []
        for hd in parsed.get("human_decisions") or []:
            hd_ids.append(HumanDecisionService(self.db).create(
                "work_product", set_wp_id, hd.get("question") or "", hd.get("reason") or "",
                hd.get("decision_type") or "OTHER"))

        task_id = self.db.execute(
            "INSERT INTO tasks(slug,title,description,status,change_id,task_type) VALUES(?,?,?,?,?,?)",
            (f"testdesign-{change_id}-{set_wp_id}", f"Test Design: {change['title'] if change else change_id}", "",
             "ACTIVE", change_id, "TEST_DESIGN"))
        self.work_products.link_task(task_id, plan_wp_id, "OUTPUT")
        self.work_products.link_task(task_id, set_wp_id, "OUTPUT")
        self.db.event("change", change_id, "TEST_DESIGN_CREATED",
                       f"plan={plan_wp_id} set={set_wp_id} cases={len(keys_seen)}")
        return {"outcome": "READY", "test_plan": self.work_products.get(plan_wp_id),
                "test_case_set": self.work_products.get(set_wp_id),
                "test_cases": self.test_case_specs.list_for_work_product(set_wp_id),
                "human_decision_ids": hd_ids, "task_id": task_id}

    def design(self, change_id: int, provider: str = "claude", project_test_command: dict | None = None) -> dict:
        change = self.changes.get(change_id)
        if not change:
            raise TestDesignError("Change not found")
        try:
            self._check_assignment(provider)
        except TestDesignError as exc:
            self.db.event("change", change_id, "TEST_DESIGN_ASSIGNMENT_INVALID", str(exc))
            return {"outcome": "ASSIGNMENT_INVALID", "test_plan": None, "message": str(exc)}

        context = self.context_builder.build(change_id, project_test_command=project_test_command)
        digest = _staleness_digest(context)
        prompt = TEST_DESIGNER_PREAMBLE + "\n\nContext:\n" + json.dumps(context, indent=2, sort_keys=True)
        try:
            raw_text = self.invoker.invoke(provider, prompt, TEST_DESIGN_JSON_SCHEMA, self.repo_root)
            parsed = json.loads(raw_text)
        except Exception as exc:
            self.db.event("change", change_id, "TEST_DESIGN_FAILED", str(exc)[:500])
            return {"outcome": "EXECUTION_FAILED", "test_plan": None, "message": str(exc)}
        if not isinstance(parsed, dict) or "strategy_summary" not in parsed or "test_cases" not in parsed:
            self.db.event("change", change_id, "TEST_DESIGN_OUTPUT_INVALID", "missing required fields")
            return {"outcome": "OUTPUT_INVALID", "test_plan": None, "message": "Missing strategy_summary/test_cases"}

        return self._store(change_id, provider, parsed, digest, None, None)

    def refine(self, test_case_set_wp_id: int, review_findings: dict, provider: str = "claude") -> dict:
        prior_set = self.work_products.get(test_case_set_wp_id)
        if not prior_set or prior_set["kind"] != "TEST_CASE_SET":
            raise TestDesignError("test_case_set_wp_id does not reference a TEST_CASE_SET WorkProduct")
        prior_plan = self.current_test_plan(prior_set["change_id"])
        change_id = prior_set["change_id"]
        context = self.context_builder.build(change_id)
        context["prior_test_cases"] = [
            {"key": tc["item_key"], "title": tc["title"], "test_level": tc["test_level"],
             "requirement_ids": json.loads(tc["requirement_ids"] or "[]"), "expected_results": tc["expected_results"]}
            for tc in self.test_case_specs.list_for_work_product(test_case_set_wp_id)
        ]
        context["review_findings"] = review_findings
        digest = _staleness_digest(context)
        prompt = (TEST_DESIGNER_PREAMBLE +
                  "\n\nYou are REFINING a prior test design based on independent review findings below. Address "
                  "every finding. Never remove a difficult test case or requirement coverage merely to make "
                  "review easier -- only strengthen, clarify, or add.\n\nContext:\n" + json.dumps(context, indent=2, sort_keys=True))
        try:
            self._check_assignment(provider)
            raw_text = self.invoker.invoke(provider, prompt, TEST_DESIGN_JSON_SCHEMA, self.repo_root)
            parsed = json.loads(raw_text)
        except TestDesignError as exc:
            self.db.event("change", change_id, "TEST_DESIGN_REFINE_ASSIGNMENT_INVALID", str(exc))
            return {"outcome": "ASSIGNMENT_INVALID", "test_plan": None, "message": str(exc)}
        except Exception as exc:
            self.db.event("change", change_id, "TEST_DESIGN_REFINE_FAILED", str(exc)[:500])
            return {"outcome": "EXECUTION_FAILED", "test_plan": None, "message": str(exc)}
        if not isinstance(parsed, dict) or "strategy_summary" not in parsed or "test_cases" not in parsed:
            self.db.event("change", change_id, "TEST_DESIGN_REFINE_OUTPUT_INVALID", "missing required fields")
            return {"outcome": "OUTPUT_INVALID", "test_plan": None, "message": "Missing strategy_summary/test_cases"}

        result = self._store(change_id, provider, parsed, digest, prior_plan["id"] if prior_plan else None, test_case_set_wp_id)
        if result["outcome"] == "READY":
            self.work_products.set_status(test_case_set_wp_id, "SUPERSEDED")
            self.test_case_specs.set_status_for_work_product(test_case_set_wp_id, "SUPERSEDED")
            if prior_plan:
                self.work_products.set_status(prior_plan["id"], "SUPERSEDED")
        return result


# ===================================================================
# Requirement Coverage Engine (E7.6/E7.7/E7.8/E7.9) -- deterministic,
# no LLM call, never trusts a model-provided coverage total
# ===================================================================
class RequirementCoverageService:
    def __init__(self, trace, test_case_specs: TestCaseSpecStore, specs_root):
        self.trace = trace
        self.test_case_specs = test_case_specs
        self.specs_root = specs_root

    def governing_feature_ids(self, change_id: int) -> list[str]:
        return [l["target_id"] for l in self.trace.for_source("change", change_id) if l["target_type"] == "spec_feature"]

    def compute(self, change_id: int) -> dict:
        from app.services.spec_registry import SpecRegistry, SpecError
        req_ids: set[str] = set()
        acc_ids: set[str] = set()
        inv_ids: set[str] = set()
        try:
            registry = SpecRegistry(self.specs_root).load()
            for fid in self.governing_feature_ids(change_id):
                f = registry.feature(fid)
                if not f:
                    continue
                req_ids.update(r["id"] for r in (f.get("requirements") or []))
                acc_ids.update(a["id"] for a in (f.get("acceptance_criteria") or []))
                inv_ids.update(i["id"] for i in (f.get("invariants") or []))
        except SpecError:
            pass

        cases = self.test_case_specs.list_for_change(change_id)
        covered_req: set[str] = set()
        covered_acc: set[str] = set()
        covered_inv: set[str] = set()
        invalid_references: list[dict] = []
        automation_candidates = 0
        manual_only_items = 0
        negative_cases = 0
        for tc in cases:
            for kind, col, universe, covered in (
                ("requirement", "requirement_ids", req_ids, covered_req),
                ("acceptance", "acceptance_ids", acc_ids, covered_acc),
                ("invariant", "invariant_ids", inv_ids, covered_inv),
            ):
                for ref in json.loads(tc[col] or "[]"):
                    if ref in universe:
                        covered.add(ref)
                    else:
                        invalid_references.append({"kind": kind, "id": ref, "test_case_key": tc["item_key"]})
            if tc["automation_candidate"]:
                automation_candidates += 1
            if tc["test_type"] == "MANUAL_ACCEPTANCE" or tc["test_level"] == "MANUAL_ACCEPTANCE":
                manual_only_items += 1
            if tc["test_type"] == "NEGATIVE":
                negative_cases += 1

        return {
            "change_id": change_id,
            "requirements_total": len(req_ids), "requirements_covered": sorted(covered_req),
            "requirements_uncovered": sorted(req_ids - covered_req),
            "acceptance_total": len(acc_ids), "acceptance_covered": sorted(covered_acc),
            "acceptance_uncovered": sorted(acc_ids - covered_acc),
            "invariants_total": len(inv_ids), "invariants_covered": sorted(covered_inv),
            "invariants_uncovered": sorted(inv_ids - covered_inv),
            "automation_candidates": automation_candidates, "manual_only_items": manual_only_items,
            "negative_cases": negative_cases, "test_case_count": len(cases),
            "invalid_references": invalid_references,
        }


# ===================================================================
# Independent Test Review (E7.10) -- a fresh invocation, reviews the
# real deterministic coverage report, never a model-claimed one
# ===================================================================
class TestReviewService(_TestAgentRole):
    def __init__(self, db, changes, work_products, invoker, roles_catalog, test_case_specs: TestCaseSpecStore,
                 coverage_service: RequirementCoverageService, specs_root, repo_root, human_decisions: HumanDecisionService):
        super().__init__(db, invoker, roles_catalog, "REVIEWER")
        self.changes = changes
        self.work_products = work_products
        self.test_case_specs = test_case_specs
        self.coverage_service = coverage_service
        self.specs_root = specs_root
        self.repo_root = repo_root
        self.human_decision_service = human_decisions

    def review(self, test_case_set_wp_id: int, provider: str = "claude") -> dict:
        from app.services.spec_registry import SpecRegistry, SpecError
        test_set = self.work_products.get(test_case_set_wp_id)
        if not test_set or test_set["kind"] != "TEST_CASE_SET":
            raise TestDesignError("test_case_set_wp_id does not reference a TEST_CASE_SET WorkProduct")
        try:
            self._check_assignment(provider)
        except TestDesignError as exc:
            self.db.event("change", test_set["change_id"], "TEST_REVIEW_ASSIGNMENT_INVALID", str(exc))
            return {"outcome": "ASSIGNMENT_INVALID", "verdict": None, "message": str(exc)}

        change_id = test_set["change_id"]
        change = self.changes.get(change_id)
        cases = self.test_case_specs.list_for_work_product(test_case_set_wp_id)
        coverage = self.coverage_service.compute(change_id)
        plan_wp = self.db.one("SELECT * FROM work_products WHERE kind='TEST_PLAN' AND change_id=? AND status!='SUPERSEDED' ORDER BY id DESC LIMIT 1", (change_id,))
        governing_specs = []
        try:
            registry = SpecRegistry(self.specs_root).load()
            for fid in self.coverage_service.governing_feature_ids(change_id):
                f = registry.feature(fid)
                if f:
                    governing_specs.append({"id": f["id"], "title": f.get("title"),
                                             "requirements": f.get("requirements"), "acceptance_criteria": f.get("acceptance_criteria"),
                                             "invariants": f.get("invariants")})
        except SpecError:
            pass
        # Deliberately the REAL, independently-computed coverage report
        # (RequirementCoverageService.compute) -- never a model-claimed
        # coverage summary (E7.10: review dimensions include requirement
        # trace correctness, which this makes checkable against ground
        # truth, not against the author's own claim).
        context = {"original_intent": change.get("description") or change.get("title") if change else None,
                   "governing_specs": governing_specs,
                   "test_strategy_summary": json.loads(plan_wp["content_metadata"] or "{}").get("strategy_summary") if plan_wp else None,
                   "test_cases": [{"key": tc["item_key"], "title": tc["title"], "test_level": tc["test_level"],
                                    "test_type": tc["test_type"], "requirement_ids": json.loads(tc["requirement_ids"] or "[]"),
                                    "acceptance_ids": json.loads(tc["acceptance_ids"] or "[]"), "invariant_ids": json.loads(tc["invariant_ids"] or "[]"),
                                    "preconditions": tc["preconditions"], "action": tc["action"], "expected_results": tc["expected_results"],
                                    "failure_expectations": tc["failure_expectations"], "automation_candidate": bool(tc["automation_candidate"])}
                                   for tc in cases],
                   "deterministic_coverage_report": coverage}
        prompt = TEST_REVIEWER_PREAMBLE + "\n\nContext:\n" + json.dumps(context, indent=2, sort_keys=True)
        try:
            raw_text = self.invoker.invoke(provider, prompt, TEST_REVIEW_JSON_SCHEMA, self.repo_root)
            parsed = json.loads(raw_text)
        except Exception as exc:
            self.db.event("change", change_id, "TEST_REVIEW_FAILED", str(exc)[:500])
            return {"outcome": "EXECUTION_FAILED", "verdict": None, "message": str(exc)}
        if not isinstance(parsed, dict) or parsed.get("verdict") not in REVIEW_VERDICTS:
            self.db.event("change", change_id, "TEST_REVIEW_OUTPUT_INVALID", "missing/unknown verdict")
            return {"outcome": "OUTPUT_INVALID", "verdict": None, "message": "Missing or unknown verdict"}

        coverage_wp_id = self.work_products.create(
            kind="REQUIREMENT_COVERAGE_REPORT", title=f"Requirement Coverage for {change['title'] if change else change_id}",
            project_id=test_set["project_id"], change_id=change_id, status="APPROVED", content_metadata=coverage)
        review_wp_id = self.work_products.create(
            kind="TEST_REVIEW", title=f"Test Review: {test_set['title']}",
            project_id=test_set["project_id"], change_id=change_id, status="DRAFT", content_metadata=parsed)
        task_id = self.db.execute(
            "INSERT INTO tasks(slug,title,description,status,change_id,task_type) VALUES(?,?,?,?,?,?)",
            (f"testreview-{test_case_set_wp_id}-{review_wp_id}", f"Test Review: {test_set['title']}", "",
             "ACTIVE", change_id, "TEST_DESIGN"))
        self.work_products.link_task(task_id, review_wp_id, "OUTPUT")

        verdict = parsed["verdict"]
        hd_ids = []
        if verdict == "PASS":
            self.work_products.set_status(test_case_set_wp_id, "APPROVED")
            self.test_case_specs.set_status_for_work_product(test_case_set_wp_id, "APPROVED")
            if plan_wp:
                self.work_products.set_status(plan_wp["id"], "APPROVED")
        elif verdict == "REJECT":
            self.work_products.set_status(test_case_set_wp_id, "REJECTED")
            self.test_case_specs.set_status_for_work_product(test_case_set_wp_id, "REJECTED")
        elif verdict == "HUMAN_DECISION_REQUIRED":
            for hd in parsed.get("human_decisions") or []:
                hd_ids.append(self.human_decision_service.create(
                    "work_product", test_case_set_wp_id, hd.get("question") or "", hd.get("reason") or "", "OTHER"))

        self.db.event("change", change_id, "TEST_REVIEWED", f"test_case_set={test_case_set_wp_id} verdict={verdict}")
        return {"outcome": "REVIEWED", "verdict": verdict, "findings": parsed.get("findings") or [],
                "coverage": coverage, "human_decision_ids": hd_ids,
                "work_product": self.work_products.get(review_wp_id), "coverage_work_product": self.work_products.get(coverage_wp_id)}


# ===================================================================
# Executable Test Mapping (E7.13/E7.14) -- explicit, human/API-confirmed
# linkage only, never unreliable semantic repo-wide guessing
# ===================================================================
class ExecutableTestMappingService:
    def __init__(self, db, test_case_specs: TestCaseSpecStore):
        self.db = db
        self.test_case_specs = test_case_specs

    def get(self, test_case_spec_id: int) -> dict | None:
        return self.db.one("SELECT * FROM test_executable_mappings WHERE test_case_spec_id=?", (test_case_spec_id,))

    def map(self, test_case_spec_id: int, repository_id: int | None, repository_path: str, test_symbol: str,
             command: str = "", framework: str = "", mapped_by: str = "HUMAN") -> dict:
        tc = self.test_case_specs.get(test_case_spec_id)
        if not tc:
            raise TestDesignError("TestCaseSpec not found")
        if not (repository_path or "").strip() or not ((test_symbol or "").strip() or (command or "").strip()):
            raise TestDesignError("Mapping requires an explicit repository_path and test_symbol/command -- E7.14: no unreliable/implicit guessing")
        existing = self.get(test_case_spec_id)
        if existing:
            self.db.execute(
                "UPDATE test_executable_mappings SET repository_id=?,repository_path=?,test_symbol=?,command=?,framework=?,"
                "implementation_status='IMPLEMENTED',mapped_by=?,updated_at=CURRENT_TIMESTAMP WHERE test_case_spec_id=?",
                (repository_id, repository_path, test_symbol, command, framework, mapped_by, test_case_spec_id))
        else:
            self.db.execute(
                "INSERT INTO test_executable_mappings(test_case_spec_id,repository_id,repository_path,test_symbol,command,framework,implementation_status,mapped_by) "
                "VALUES(?,?,?,?,?,?,?,?)",
                (test_case_spec_id, repository_id, repository_path, test_symbol, command, framework, "IMPLEMENTED", mapped_by))
        self.db.event("task", test_case_spec_id, "TEST_EXECUTABLE_MAPPED", f"path={repository_path} symbol={test_symbol}")
        return self.get(test_case_spec_id)

    def record_result(self, test_case_spec_id: int, status: str, last_result_reference: str | None = None) -> dict:
        status = (status or "").strip().upper()
        if status not in ("PASS", "FAIL"):
            raise TestDesignError("record_result status must be PASS or FAIL -- a designed-but-unexecuted test is never recorded as either")
        existing = self.get(test_case_spec_id)
        if not existing:
            raise TestDesignError("No executable mapping exists for this TestCaseSpec yet -- map it before recording a result")
        self.db.execute(
            "UPDATE test_executable_mappings SET implementation_status=?,last_result_reference=?,updated_at=CURRENT_TIMESTAMP WHERE test_case_spec_id=?",
            (status, last_result_reference, test_case_spec_id))
        return self.get(test_case_spec_id)

    def status_for_change(self, change_id: int) -> list[dict]:
        out = []
        for tc in self.test_case_specs.list_for_change(change_id):
            m = self.get(tc["id"])
            out.append({"test_case_spec_id": tc["id"], "item_key": tc["item_key"],
                         "implementation_status": m["implementation_status"] if m else "UNIMPLEMENTED",
                         "mapping": m})
        return out


def test_design_state_digest(work_products, change_id: int) -> str | None:
    """E7.16: a digest of the CURRENT (non-SUPERSEDED) test-design
    WorkProduct state governing a Change -- used by PlannerService to
    detect PLAN_TEST_DESIGN_STALE, mirroring E6.17's design_state_digest
    exactly."""
    kinds = ("TEST_PLAN", "TEST_CASE_SET", "TEST_REVIEW", "REQUIREMENT_COVERAGE_REPORT")
    rows = [wp for wp in work_products.list_for_change(change_id) if wp["kind"] in kinds and wp["status"] != "SUPERSEDED"]
    if not rows:
        return None
    fingerprint = sorted((wp["kind"], wp["id"], wp["status"], wp["updated_at"]) for wp in rows)
    return hashlib.sha256(json.dumps(fingerprint, sort_keys=True).encode()).hexdigest()


# ===================================================================
# TestDesignLifecycleService -- bounded refinement loop (E7.11) + read
# helpers + WorkflowService gate evidence (E7.17) + Planner metadata
# (E7.15/E7.16)
# ===================================================================
class TestDesignLifecycleService:
    MAX_ROUNDS = 3

    def __init__(self, db, changes, work_products, trace, context_builder: TestDesignContextBuilder,
                 test_design: TestDesignService, coverage: RequirementCoverageService, review: TestReviewService,
                 test_case_specs: TestCaseSpecStore, executable_mapping: ExecutableTestMappingService,
                 human_decisions: HumanDecisionService, workflow_service=None):
        self.db = db
        self.changes = changes
        self.work_products = work_products
        self.trace = trace
        self.context_builder = context_builder
        self.test_design = test_design
        self.coverage = coverage
        self.review = review
        self.test_case_specs = test_case_specs
        self.executable_mapping = executable_mapping
        self.human_decision_service = human_decisions
        self.workflow_service = workflow_service

    # ---- read -----------------------------------------------------
    def current_test_case_set(self, change_id: int) -> dict | None:
        return self.test_design.current_test_case_set(change_id)

    def current_test_plan(self, change_id: int) -> dict | None:
        return self.test_design.current_test_plan(change_id)

    def unimplemented_test_cases(self, change_id: int) -> list[dict]:
        return [s for s in self.executable_mapping.status_for_change(change_id) if s["implementation_status"] == "UNIMPLEMENTED"]

    def status(self, change_id: int) -> dict:
        test_set = self.current_test_case_set(change_id)
        plan = self.current_test_plan(change_id)
        coverage_report = self.coverage.compute(change_id)
        unimplemented = self.unimplemented_test_cases(change_id)
        return {
            "change_id": change_id, "test_plan": plan, "test_case_set": test_set,
            "coverage": coverage_report, "test_implementation_required": bool(unimplemented),
            "unimplemented_test_cases": unimplemented,
            "test_design_ready": self.test_design_ready(change_id),
        }

    def _resolve_profile_key(self, change_id: int) -> str | None:
        if not self.workflow_service:
            return None
        run = self.workflow_service.get_workflow(change_id)
        return run["profile_key"] if run else None

    # ---- WorkflowService gate evidence (E7.17) ------------------------
    def test_design_ready(self, change_id: int, profile_key: str | None = None) -> bool:
        governing_ids = self.coverage.governing_feature_ids(change_id)
        if not governing_ids:
            # E7.17/E7.7: nothing governs this Change at the Change-level
            # spec trace-link -- vacuously ready, the same "nothing to
            # require" direction E6's architecture/design gates use.
            return True
        test_set = self.current_test_case_set(change_id)
        if not test_set or test_set["status"] != "APPROVED":
            return False
        if self.human_decision_service.pending_for_change(change_id):
            return False
        coverage_report = self.coverage.compute(change_id)
        if coverage_report["requirements_uncovered"]:
            return False
        profile_key = profile_key if profile_key is not None else self._resolve_profile_key(change_id)
        if profile_key == "CONTROLLED":
            if coverage_report["acceptance_uncovered"]:
                return False
            if coverage_report["invariants_total"] and coverage_report["invariants_uncovered"]:
                return False
        return True

    # ---- staleness (E7.21) --------------------------------------------
    def staleness(self, change_id: int) -> dict:
        """TEST_SPEC_STALE: the bounded context (governing spec text +
        approved architecture/design) that produced the CURRENT
        TestCaseSet has changed since generation -- a minimal digest-
        based check, same discipline as E5/E6 (never auto-deletes a
        test). EXECUTABLE_TEST_MAPPING_STALE: an executable mapping
        whose TestCaseSpec has since been SUPERSEDED by a refinement."""
        test_set = self.current_test_case_set(change_id)
        test_spec_stale = False
        current_digest = stored_digest = None
        if test_set:
            stored_digest = test_set.get("content_digest")
            current_context = self.context_builder.build(change_id)
            current_digest = _staleness_digest(current_context)
            test_spec_stale = bool(stored_digest) and stored_digest != current_digest
        stale_mappings = []
        for tc in self.test_case_specs.list_for_change(change_id, current_only=False):
            if tc["status"] != "SUPERSEDED":
                continue
            m = self.executable_mapping.get(tc["id"])
            if m:
                stale_mappings.append({"test_case_spec_id": tc["id"], "item_key": tc["item_key"]})
        return {
            "change_id": change_id,
            "test_spec_stale": test_spec_stale, "reason": "TEST_SPEC_STALE" if test_spec_stale else None,
            "stored_digest": stored_digest, "current_digest": current_digest,
            "executable_test_mapping_stale": stale_mappings,
        }

    # ---- bounded refinement loop (E7.11) ------------------------------
    def run_design(self, change_id: int, provider: str = "claude", max_rounds: int | None = None,
                    project_test_command: dict | None = None) -> dict:
        max_rounds = max_rounds if max_rounds is not None else self.MAX_ROUNDS
        result = self.test_design.design(change_id, provider=provider, project_test_command=project_test_command)
        if result["outcome"] != "READY":
            return {"outcome": result["outcome"], "stage": "TEST_DESIGN", "message": result.get("message"),
                    "test_case_set": None, "rounds": 0}
        set_id = result["test_case_set"]["id"]

        for round_no in range(max_rounds):
            review = self.review.review(set_id, provider=provider)
            if review["outcome"] != "REVIEWED":
                return {"outcome": review["outcome"], "stage": "TEST_REVIEW", "message": review.get("message"),
                        "test_case_set": self.work_products.get(set_id), "rounds": round_no}
            verdict = review["verdict"]
            if verdict == "PASS":
                return {"outcome": "TEST_DESIGN_READY", "test_case_set": self.work_products.get(set_id),
                        "coverage": review["coverage"], "verdict": verdict, "rounds": round_no + 1}
            if verdict in ("HUMAN_DECISION_REQUIRED", "REJECT"):
                return {"outcome": "HUMAN_DECISION_REQUIRED" if verdict == "HUMAN_DECISION_REQUIRED" else "REJECTED",
                        "test_case_set": self.work_products.get(set_id), "coverage": review["coverage"],
                        "verdict": verdict, "rounds": round_no + 1}
            if round_no + 1 >= max_rounds:
                return {"outcome": "NEEDS_REFINEMENT", "test_case_set": self.work_products.get(set_id),
                        "coverage": review["coverage"], "verdict": verdict, "rounds": round_no + 1,
                        "message": f"Refinement round limit ({max_rounds}) reached"}
            refined = self.test_design.refine(set_id, review, provider=provider)
            if refined["outcome"] != "READY":
                return {"outcome": refined["outcome"], "stage": "TEST_DESIGN_REFINE", "message": refined.get("message"),
                        "test_case_set": self.work_products.get(set_id), "rounds": round_no + 1}
            set_id = refined["test_case_set"]["id"]

        return {"outcome": "NEEDS_REFINEMENT", "test_case_set": self.work_products.get(set_id), "rounds": max_rounds}
